---
language: ruby
bundler_args: --without system_tests
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="no"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="no"
sudo: false
branches:
  only:
    - master
